### ISSUE TITLE
wrong default_offer despite configuration

### ISSUE THREAD

**Issue by psycofdj** [orange-cloudfoundry/bosh-go-cpi-cloudstack#1]
properties:

```yaml
cloud_provider:
  properties:
    cloudstack:
      default_offer:
        custom_disk: ""
        disk: shared.small.scaleio
        ephemeral_disk: shared.medium.scaleio
```

generated cpi configuration:
```json
{
   "CloudStack" : {
      "DefaultOffer" : {
         "CustomDisk" : "shared.custom",
         "Disk" : "",
         "EphemeralDisk" : ""
      }
  }
}
```

**Comment by psycofdj** [comment]
Problem actually occured because default offer sould also be overriden in bosh instance_group (in addition to cloud_provider)

```
- type: replace
  path: /instance_groups/name=bosh/properties/cloudstack/default_offer
  value:
    custom_disk: ""
    disk: shared.small.scaleio
    ephemeral_disk: shared.medium.scaleio
```
